allowBuilds:
  '@prisma/engines': true
  '@nestjs/core': true
  esbuild: true
  prisma: true
  protobufjs: true
  '@apollo/protobufjs': true
  argon2: true
minimumReleaseAgeExclude:
  - '@omnixys/cache-ts@4.0.0'
  - '@omnixys/context-ts@4.0.2'
  - '@omnixys/contracts-ts@4.0.0'
  - '@omnixys/graphql-ts@4.0.0'
  - '@omnixys/grpc-ts@2.0.0'
  - '@omnixys/http-ts@2.0.0'
  - '@omnixys/logger-ts@4.0.0'
  - '@omnixys/observability-ts@4.0.0'
  - '@omnixys/security-ts@5.0.0'
overrides:
  fastify: 5.8.5
